# Homebrew formula for flywheel-cli.
#
# This is the starter formula. It belongs in a *tap* repo — create
# github.com/ydderd/homebrew-flywheel and place this file at Formula/flywheel-cli.rb.
# Customers then install with:
#
#     brew install ydderd/flywheel/flywheel-cli
#
# The `url`/`sha256` below are filled in by cli/scripts/release.sh after publishing to PyPI,
# and the `resource` blocks (httpx, boto3, and their transitive deps) are generated by:
#
#     brew update-python-resources Formula/flywheel-cli.rb
#
class FlywheelCli < Formula
  include Language::Python::Virtualenv

  desc "Authenticate and bulk-upload field data to your Flywheel workspace"
  homepage "https://withflywheel.com"
  # release.sh replaces the two PLACEHOLDER lines with the PyPI sdist URL + sha256.
  url "PLACEHOLDER_SDIST_URL"
  sha256 "PLACEHOLDER_SHA256"
  license "Apache-2.0"

  depends_on "python@3.12"

  # BEGIN RESOURCES — populated by `brew update-python-resources`. Do not edit by hand.
  # END RESOURCES

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "usage: flywheel", shell_output("#{bin}/flywheel --help")
  end
end
